package java_04.incap;

import java_04.annot.NonNull;

import java.util.Objects;
import java.util.Random;

public class MobilePhone {
    private static final Random rnd = new Random();
    private static final int RANGE_ID = 10000;

    private final int mId;
    private final String mModel;
    private final String mBrand;
    private final String mColor;
    private final double mPrice;


    private MobilePhone(int id, String brand, String model, String color, double price) {
        this.mModel = model;
        this.mBrand = brand;
        this.mColor = color;
        this.mPrice = price;
        this.mId = id;
    }

    private MobilePhone(String brand, String model, String color, double price) {
        this(rnd.nextInt(RANGE_ID), brand, model, color, price);
    }

    public String getBrand() {
        return mBrand;
    }

    double getPrice() {
        return mPrice;
    }


// autogenerated by Java8
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof MobilePhone)) return false;
        MobilePhone that = (MobilePhone) o;
        return mId == that.mId &&
                Double.compare(that.mPrice, mPrice) == 0 &&
                Objects.equals(mModel, that.mModel) &&
                Objects.equals(mBrand, that.mBrand) &&
                Objects.equals(mColor, that.mColor);
    }

    @Override
    public int hashCode() {

        return Objects.hash(mId, mModel, mBrand, mColor, mPrice);
    }

    @Override
    public String toString() {
        return String.format("ID: %02d Brand: %-8s Model: %-10s Color: %-8s Price: %-8.2f",
                mId, mBrand, mModel, mColor, mPrice);
    }

    private static <T> void checkForNull(T obj) {
        if (obj == null) {
            throw new NullPointerException();
        }
        if (obj instanceof Double && (Double) obj < 0) {
            throw new NullPointerException();
        }
        if (obj instanceof Integer && (Integer) obj < 0) {
            throw new NullPointerException();
        }
    }

    // NonNull with User Annotation and IDEA support
    static MobilePhone newInstance(int id, @NonNull String brand, String model, String color, double price) {
        validateParameters(id, brand, model, color, price);
        return new MobilePhone(id, brand, model, color, price);
    }

    static MobilePhone newInstance(String brand, String model, String color, double price) {
        validateParameters(brand, model, color, price);
        return new MobilePhone(brand, model, color, price);
    }

    // NonNull with standard Methods
    private static void validateParameters(String brand, String model, String color, double price) {
//  brand check  inactive and blocked by @NonNull
        Objects.requireNonNull(brand);                             // no message
        Objects.requireNonNull(model, () -> "No Model Message");  // supplier
        Objects.requireNonNull(color, "No Color data");   // string
        checkForNull(price);
    }

    // NonNull with custom Methods
    private static void validateParameters(int id, String brand, String model, String color, double price) {
        checkForNull(id);
        validateParameters(brand, model, color, price);
    }
}
